version: '3.7'
services:
  bot:
    build: .
    environment:
      - TOKEN=your_discord_bot_token
      - SERVER_IP=your_bf2_servers_ip
      - SERVER_PORT=your_bf2_servers_game_port
      - BOT_TREATMENT=ignore
      - LOG_LEVEL=info
